In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel('한국어_단발성_대화_데이터셋.xlsx')
df

,Sentence,Emotion,Unnamed: 2,Unnamed: 3,Unnamed: 4,공포,5468
0,언니 동생으로 부르는게 맞는 일인가요..??,공포,NaN,NaN,NaN,놀람,5898.0
1,그냥 내 느낌일뿐겠지?,공포,NaN,NaN,NaN,분노,5665.0
2,아직너무초기라서 그런거죠?,공포,NaN,NaN,NaN,슬픔,5267.0
3,유치원버스 사고 낫다던데,공포,NaN,NaN,NaN,중립,4830.0
4,근데 원래이런거맞나요,공포,NaN,NaN,NaN,행복,6037.0
...,...,...,...,...,...,...,...
38589,솔직히 예보 제대로 못하는 데 세금이라도 아끼게 그냥 폐지해라..,혐오,NaN,NaN,NaN,NaN,NaN
38590,재미가 없으니 망하지,혐오,NaN,NaN,NaN,NaN,NaN
38591,공장 도시락 비우생적임 아르바이트했는데 화장실가성 손도 않씯고 재료 담고 바닥 떨어...,혐오,NaN,NaN,NaN,NaN,NaN
38592,코딱지 만한 나라에서 지들끼리 피터지게 싸우는 센징 클래스 ㅉㅉㅉ,혐오,NaN,NaN,NaN,NaN,NaN
38593,와이프도 그렇고 댓글 다 볼텐데 이휘재 좀 하차 하라고 전해주세요,혐오,NaN,NaN,NaN,NaN,NaN

In [10]:
df = df.dropna(axis=1)
df

                                                Sentence Emotion
0                               언니 동생으로 부르는게 맞는 일인가요..??      공포
1                                           그냥 내 느낌일뿐겠지?      공포
2                                         아직너무초기라서 그런거죠?      공포
3                                          유치원버스 사고 낫다던데      공포
4                                            근데 원래이런거맞나요      공포
...                                                  ...     ...
38589               솔직히 예보 제대로 못하는 데 세금이라도 아끼게 그냥 폐지해라..      혐오
38590                                        재미가 없으니 망하지      혐오
38591  공장 도시락 비우생적임 아르바이트했는데 화장실가성 손도 않씯고 재료 담고 바닥 떨어...      혐오
38592               코딱지 만한 나라에서 지들끼리 피터지게 싸우는 센징 클래스 ㅉㅉㅉ      혐오
38593               와이프도 그렇고 댓글 다 볼텐데 이휘재 좀 하차 하라고 전해주세요      혐오

[38594 rows x 2 columns]

In [20]:
df.replace({"행복": 0, "중립": 1, "슬픔":2, "분노":3})
df

                                                Sentence Emotion
0                               언니 동생으로 부르는게 맞는 일인가요..??      공포
1                                           그냥 내 느낌일뿐겠지?      공포
2                                         아직너무초기라서 그런거죠?      공포
3                                          유치원버스 사고 낫다던데      공포
4                                            근데 원래이런거맞나요      공포
...                                                  ...     ...
38589               솔직히 예보 제대로 못하는 데 세금이라도 아끼게 그냥 폐지해라..      혐오
38590                                        재미가 없으니 망하지      혐오
38591  공장 도시락 비우생적임 아르바이트했는데 화장실가성 손도 않씯고 재료 담고 바닥 떨어...      혐오
38592               코딱지 만한 나라에서 지들끼리 피터지게 싸우는 센징 클래스 ㅉㅉㅉ      혐오
38593               와이프도 그렇고 댓글 다 볼텐데 이휘재 좀 하차 하라고 전해주세요      혐오

[38594 rows x 2 columns]

In [26]:
df_n= df.replace(["공포", "놀람","혐오"], np.nan)

In [27]:
df_n= df_n.dropna(axis=0)

In [29]:
df_new= df_n.replace({"행복": 0, "중립": 1, "슬픔":2, "분노":3})
df_new

                          Sentence  Emotion
11366  서해 수자원도 한류라서 그동안 불법조업 방치했나?        3
11367                     니가 인간이가.        3
11368    강아지를 때리고 유기하는것만 학대는 아닙니다!        3
11369        하여간 우리나라 교육엔 미래가 없어!!        3
11370     채널에이 군부 개인거 인증하냐 동아일보야!!        3
...                            ...      ...
33160       유느님 내일 이면 해피투게더가하네요~^^        0
33161      승관아~ 너에게 편지를 안 쓸 수가 없네.        0
33162  패떴 개그계 큰 대모 이경실 씨 1탄 잘 봤습니다        0
33163   유재석 오라버니 해피투게더 해피파출소 편 봤어요        0
33164           유재석 오라버니 해피투게더 봤어요        0

[21799 rows x 2 columns]